
En Postman comprobamos las rutas de nuestra API.

ENCONTRAR USUARIO
  GET: http://localhost:3000/usuario

ENTRENAMIENTOS
# Obtener todos los entrenamientos
GET: http://localhost:3000/entrenamiento

# Filtrar por nivel ($eq o $in) y duración ($gte / $lte)
GET: http://localhost:3000/entrenamiento?nivel=Principiante,Intermedio&minDuracion=20&maxDuracion=45

# Filtrar por material exacto ($eq) y por duración estricta ($gt / $lt)
GET: http://localhost:3000/entrenamiento?material=Mancuernas&duracionMayorQue=15&duracionMenorQue=60

# Crear entrenamiento
http://localhost:3000/entrenamiento


# Obtener entrenamiento por ID
GET http://localhost:3000/entrenamiento/ID_AQUI

# Eliminar entrenamiento
DELETE http://localhost:3000/entrenamiento/ID_AQUI